apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: food-delivery-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: food-delivery
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: food-delivery-backend
    app.kubernetes.io/component: backend